### ISSUE TITLE
Database Schema Review

### ISSUE THREAD

**Issue by BCrawfordScott** [RobertVogue/Passport#15]
Great work team, thank you for taking our suggestions.  A few more notes for you:

- [x] Add createdAt and updatedAt to all tables
- [x] Name vs status on passport: I assume that `passport_status` will be used to determine things like "visited," "visiting,", "want to visit."  If that's the case, why not just make that the name of the passport?
- [x] Rating: Is this a static property of the stamp, or is this something that will be updated/recalculated as more people leave reviews?  If it's the latter, perhaps it's better to add the `rating` column onto the `reviews` table, then you can dynamically calculate the rating by pulling all of the stamp's reviews.
- [x] Add a `stamp_tags` table: Stamps can have many tags, and tags can have many stamps.
   - [x] Remove '`tag_id` from the stamps table
- [x] remove `detailed_location` and `dates` from `Stamps`: Those pieces of data are specific to a user interacting with a stamp. 
 Stamps are going to be re-used by many users, for example: User Mary visits Cairo, gets the 'Egypt' stamp.  User Bob then visits Cairo, gets the 'Egypt' stamp.  We don't want two different stamps for the same country.   If we want to capture information about Mary or Bob's trips to Cairo (ie, their interactions with the 'Egypt' stamp) we would create another joins table: `user_stamps` or `visits` to be more converstional that joins many to many users to stamps.  I recommend doing this as a bonus feature.
 
 Keep up the great work!

**Comment by RobertVogue** [comment]
Cleared.
