### ISSUE TITLE
Set up Milestones for Project

### ISSUE THREAD

**Issue by pantheman1** [RobertVogue/Passport#8]
### Milestones
- [x] User Auth
- [x] Navbar/Footer
- [x] Stamps
- [x] Reviews
- [x] Profile/Passport Page
- [x] Home Page

**Comment by pantheman1** [comment]
@V3RS @raymondmay95 @RobertVogue  Could you guys please review the list of Milestones I created in this task to see if any are missing? These milestones are not tasks, only major events that we are shooting to hit by completing tasks. We can discuss Monday.

**Comment by raymondmay95** [comment]
Footer?

**Comment by RobertVogue** [comment]
Well Done Peter! These looks great!

**Comment by pantheman1** [comment]
> Footer?

Great catch! I will add this to the Navbar unless you guys think the footer needs it's own Milestone.

**Comment by V3RS** [comment]
Looks good!
